//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFAWater.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public int Durum { get; set; }
        public decimal Tutar { get; set; }
        public bool isDeleted { get; set; }
        public System.DateTime KayitTarihi { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
